require('bathcat.set')
require('bathcat.plugins')
require('bathcat.set_plugins')
require('bathcat.remap')
require('bathcat.lsp')
require('bathcat.cmp')
require('bathcat.debug')
require('bathcat.telescope')
